---
title: '【学習メモ】JavaScriptコードレシピ集 その15'
description: ''
pubDate: 04/23/2019 21:00:00
---

<p>JavaScriptコードレシピ集 の学習メモ 続きです。</p>

<p><div class="hatena-asin-detail"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4297103680/hatena-blog-22/"><img src="https://cdn-ak.f.st-hatena.com/images/fotolife/j/jotaki/20190726/20190726111820.jpg" class="hatena-asin-detail-image" alt="JavaScript コードレシピ集" title="JavaScript コードレシピ集"></a><div class="hatena-asin-detail-info"><p class="hatena-asin-detail-title"><a href="http://www.amazon.co.jp/exec/obidos/ASIN/4297103680/hatena-blog-22/">JavaScript コードレシピ集</a></p><ul><li><span class="hatena-asin-detail-label">作者:</span> 池田泰延,鹿野壮</li><li><span class="hatena-asin-detail-label">出版社/メーカー:</span> 技術評論社</li><li><span class="hatena-asin-detail-label">発売日:</span> 2019/01/25</li><li><span class="hatena-asin-detail-label">メディア:</span> 単行本（ソフトカバー）</li><li><a href="http://d.hatena.ne.jp/asin/4297103680/hatena-blog-22" target="_blank">この商品を含むブログを見る</a></li></ul></div><div class="hatena-asin-detail-foot"></div></div></p>

<h2>Chapter17 プログラムのデバッグ</h2>

<p><code>console.log()</code> しか使ってきませんでしたがいろいろ便利そうです。<code>console.table()</code> とか</p>

<h3>251 情報・エラー・警告を出力したい</h3>

<pre class="code lang-javascript" data-lang="javascript" data-unlink>console.log(<span class="synConstant">'ログです'</span>);
console.info(<span class="synConstant">'情報です'</span>);
console.warn(<span class="synConstant">'警告です'</span>);
console.error(<span class="synConstant">'エラーです'</span>);
</pre>

<h3>252 オブジェクトの構造を出力したい</h3>

<p><code>console.dir()</code> はオブジェクト構造を出力できる</p>

<pre class="code lang-javascript" data-lang="javascript" data-unlink><span class="synStatement">const</span> item252_myObject = <span class="synIdentifier">{</span>
  id: 2,
  name: <span class="synConstant">'鈴木'</span>
<span class="synIdentifier">}</span>;
console.dir(item252_myObject);

<span class="synComment">// body要素の構造を出力</span>
console.dir(<span class="synStatement">document</span>.body);
<span class="synComment">// baseURI を出力</span>
console.dir(<span class="synStatement">document</span>.body.baseURI); <span class="synComment">// 結果: http://127.0.0.1:5500/dist/index.html</span>
</pre>

<p><code>console.table()</code> はデータが表組みで表示される</p>

<pre class="code lang-javascript" data-lang="javascript" data-unlink><span class="synStatement">const</span> item252_myArray = <span class="synIdentifier">[</span>
  <span class="synIdentifier">{</span> id: 100, name: <span class="synConstant">'鈴木'</span>, age: 25 <span class="synIdentifier">}</span>,
  <span class="synIdentifier">{</span> id: 200, name: <span class="synConstant">'田中'</span>, age: 30 <span class="synIdentifier">}</span>,
  <span class="synIdentifier">{</span> id: 300, name: <span class="synConstant">'太郎'</span>, age: 35 <span class="synIdentifier">}</span>
<span class="synIdentifier">]</span>;
console.table(item252_myArray);
</pre>

<h3>254 <code>Error</code> オブジェクトを生成したい</h3>

<blockquote><p>エラーはプログラム実行中に自動で発生する他、開発者側で発生させることも可能です。「エラーを投げる（throw error）」と表現します。関数に不正な値が渡された場合やAPIの戻り値が意図せぬ値になった場合などに使用します。</p></blockquote>

<pre class="code lang-javascript" data-lang="javascript" data-unlink><span class="synComment">// Error オブジェクトのインスタンス化</span>
<span class="synStatement">const</span> item254_error = <span class="synStatement">new</span> Error(<span class="synConstant">'エラーが発生しました'</span>);
console.log(item254_error.message); <span class="synComment">// 結果: エラーが発生しました</span>
</pre>

<h3>255 エラーを投げたい</h3>

<p>API通信時に不正な値が発見されたらエラー扱いにしたいときなどに使用できる</p>

<pre class="code lang-javascript" data-lang="javascript" data-unlink><span class="synComment">/** 引数value が数値でない場合にエラーを発生させる関数 */</span>
<span class="synIdentifier">function</span> item255_myFunction(value) <span class="synIdentifier">{</span>
  <span class="synStatement">if</span> (<span class="synStatement">typeof</span> value !== <span class="synConstant">'number'</span>) <span class="synIdentifier">{</span>
    <span class="synComment">// エラーを生成する</span>
    <span class="synStatement">const</span> item255_error = <span class="synStatement">new</span> Error(`「$<span class="synIdentifier">{</span>value<span class="synIdentifier">}</span>はNumberではありません」`);
    <span class="synComment">// エラー内容をコンソールで表示する</span>
    console.log(item255_error);
    <span class="synComment">// エラーを投げる</span>
    <span class="synStatement">throw</span> item255_error;
  <span class="synIdentifier">}</span>

  console.log(`「$<span class="synIdentifier">{</span>value<span class="synIdentifier">}</span>」は数値です`);
<span class="synIdentifier">}</span>

<span class="synComment">// 関数に数値を渡す（エラーなし）</span>
item255_myFunction(5); <span class="synComment">// 結果: 「5」は数値です</span>
<span class="synComment">// 関数に文字列を渡す（エラーが発生する）</span>
item255_myFunction(<span class="synConstant">'鈴木'</span>); <span class="synComment">// 結果: Uncaught Error: 「鈴木はNumberではありません」</span>
</pre>

<h3>256 エラー発生時にエラーを検知したい</h3>

<blockquote><p>コンテンツによってはエラーが発生しても処理を中断せず、続けたい場合もあるでしょう。そのような場合に使うのが <code>try catch</code> です。<code>try {}</code> の部分でエラーが発生すると、<code>catch(error) {}</code> 部分が実行されます。<code>catch(error) {}</code> 部分ではErrorオブジェクトを受けとり、エラー内容の表示などが可能です。</p></blockquote>

<pre class="code lang-javascript" data-lang="javascript" data-unlink><span class="synStatement">const</span> item256_a = 10;

<span class="synStatement">try</span> <span class="synIdentifier">{</span>
  item256_a = 20; <span class="synComment">// aへの再代入 エラー</span>
<span class="synIdentifier">}</span> <span class="synStatement">catch</span> (error) <span class="synIdentifier">{</span>
  console.log(`エラーが発生しました: $<span class="synIdentifier">{</span>error.messsage<span class="synIdentifier">}</span>`);
<span class="synIdentifier">}</span>

<span class="synComment">// 中断されることなく実行される</span>
console.log(`定数item256_aの値は$<span class="synIdentifier">{</span>item256_a<span class="synIdentifier">}</span>です`); <span class="synComment">// 結果: 定数item256_aの値は10です</span>
</pre>

<h3>258 エラーの種類について知りたい</h3>

<table>
<thead>
<tr>
<th> 種類             </th>
<th> 意味                                   </th>
</tr>
</thead>
<tbody>
<tr>
<td> <code>RangeError</code>     </td>
<td> 値が許容範囲にない                     </td>
</tr>
<tr>
<td> <code>ReferenceError</code> </td>
<td> 宣言されていない変数を読み出そうとした </td>
</tr>
<tr>
<td> <code>SyntaxError</code>    </td>
<td> 言語の構文が不正                       </td>
</tr>
<tr>
<td> <code>TypeErrror</code>     </td>
<td> データ型が不正                         </td>
</tr>
<tr>
<td> <code>URIError</code>       </td>
<td> URIが不正                              </td>
</tr>
</tbody>
</table>

<hr />

<p>最後の2章、</p>

<ul>
<li>Chapter 18 関数やクラスについて詳しく知る</li>
<li>Chapter 19 JavaScriptをより深く知る</li>
</ul>

<p>はちょっと発展的な内容なのでスキップします。</p>

<h2>まとめ</h2>

<p>最後はちょっと飛ばし飛ばしになりましたが、一通り1冊終えることができました。</p>

<p>良かったこととして、</p>

<ul>
<li>JavaScript でできる基本的なことを網羅的に理解ができた。（おそらく）</li>
<li><code>.addEventListener()</code> やアロー関数など、手打ちしていっただの繰り返し書いた記述ものに関しては構文が染み付いた</li>
<li>インデントの使い方など、規約的なところでの標準もなんとなく理解できた（それが正でないにしても）</li>
</ul>

<p>まだまだなこととして、</p>

<ul>
<li>これら学んだ内容を実戦でどの程度使えるようになるのかを具体的に分かっていない</li>
</ul>

<p>ことがあります。</p>

<p>ともかく1番良かったのは、JavaScript に対しての壁が低く感じれるようになったことでした。</p>
